# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: EMDOC
author: Richard G. Edwards
copyright: "2025, Richard G. Edwards"  # Added a copyright notice
logo: logo.svg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: emdoc.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/your-username/your-repo-name  # <-- PLEASE UPDATE
  path_to_book: jb  # Assuming 'jb' is the path to your book in the repo
  branch: main  # Default branch is now 'main' on GitHub

# Add numbering to chapters and sections
parse:
  myst_number_sections: true

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true